#文件路径
###########解析excel路径
#本地
#target: D:\00-2021-mdb\testXls1000\
#服务器
target: //usr//local//testxls//

###########解析MDB路径
#本地
#targetMDB: D:\\00-2021-mdb\\test1000\\
#服务器
targetMDB: //usr//local//testmdb//

server:
  port: 8080

logging:
  level:
    com.tj.resolvedemo.test: INFO

mybatis:
  mapper-locations: classpath:/mappers/*.xml

spring:
  profiles:
    active: mysql_dev